sudo: required
dist: trusty

install:
  - bundle install --full-index --jobs=3 --retry=3

script:
  - bundle exec rake test_app
  - bundle exec rake spec

env:
  global:
    - AVATAX_COMPANY_CODE=test_company
    - AVATAX_ACCOUNT=test_account
    - AVATAX_LICENSE_KEY=test_license_key
    - AVATAX_ENDPOINT=https://development.avalara.net
    - RAILS_ENV=test
    - RACK_ENV=test
  matrix:
    - DB=mysql
    - DB=postgres

language: ruby

rvm:
  - 2.4.2
  - 2.3.1
  - 2.2.7

gemfile:
  - gemfiles/spree_3_1.gemfile
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_3_3.gemfile
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
  - gem install spree -v '~> 3.1.0'
  - gem install codeclimate-test-reporter
  - gem install pry
  - gem install rails-controller-testing
  - gem install rails_test_params_backport